name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: 'rustfmt, clippy'

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features
  rust:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '${{ matrix.toolchain }}'

      - name: Compile Tests
        run: cargo test --all-features --no-run

      - name: Run Tests
        run: cargo test --all-features --verbose

      - name: Run Doc Tests
        run: cargo test --doc --all-features --verbose
